module.exports = {
  title: "テック無尽 企画書",
  author: "テック無尽実行委員会",
  language: "ja",
  size: "A4",
  entry: [
    { path: "docs/00-cover.md", title: "表紙" },
    { path: "docs/01-background.md", title: "はじめに（背景・問題意識）" },
    { path: "docs/02-purpose.md", title: "目的" },
    { path: "docs/03-concept.md", title: "コンセプト" },
    { path: "docs/04-overview.md", title: "イベント概要" },
    { path: "docs/05-persona.md", title: "ターゲット・ペルソナ" },
    { path: "docs/06-program.md", title: "プログラム構成" },
    { path: "docs/07-timetable.md", title: "タイムテーブル" },
    { path: "docs/08-venue-design.md", title: "会場設計" },
    { path: "docs/09-value.md", title: "提供価値" },
    { path: "docs/10-participation.md", title: "参加方法" },
    { path: "docs/11-sponsorship.md", title: "スポンサーシップ" },
    { path: "docs/12-marketing.md", title: "広報・集客" },
    { path: "docs/13-organization.md", title: "運営体制" },
    { path: "docs/14-schedule.md", title: "準備スケジュール" },
    { path: "docs/15-budget.md", title: "予算" },
    { path: "docs/16-risk.md", title: "リスクと対策" },
    { path: "docs/17-track-record.md", title: "実績" },
    { path: "docs/18-future.md", title: "今後の展望" },
    { path: "docs/19-contact.md", title: "お問い合わせ" },
    { path: "docs/20-appendix.md", title: "付録" },
  ],
  output: "output.pdf",
  theme: "themes/custom.css",
};
