module.exports = {
  title: "テック無尽 企画書",
  author: "テック無尽実行委員会",
  language: "ja",
  size: "A4",
  entry: [
    { path: "docs/cover.md", title: "表紙" },
    { path: "docs/background.md", title: "はじめに（背景・問題意識）" },
    { path: "docs/purpose.md", title: "目的" },
    { path: "docs/concept.md", title: "コンセプト" },
    { path: "docs/overview.md", title: "イベント概要" },
    { path: "docs/persona.md", title: "ターゲット・ペルソナ" },
    { path: "docs/program.md", title: "プログラム構成" },
    { path: "docs/timetable.md", title: "タイムテーブル" },
    { path: "docs/venue-design.md", title: "会場設計" },
    { path: "docs/value.md", title: "提供価値" },
    { path: "docs/participation.md", title: "参加方法" },
    { path: "docs/sponsorship.md", title: "スポンサーシップ" },
    { path: "docs/marketing.md", title: "広報・集客" },
    { path: "docs/organization.md", title: "運営体制" },
    { path: "docs/schedule.md", title: "準備スケジュール" },
    { path: "docs/budget.md", title: "予算" },
    { path: "docs/risk.md", title: "リスクと対策" },
    { path: "docs/track-record.md", title: "実績" },
    { path: "docs/future.md", title: "今後の展望" },
    { path: "docs/contact.md", title: "お問い合わせ" },
    { path: "docs/appendix.md", title: "付録" },
  ],
  output: "output.pdf",
};
