module.exports = {
  title: "テック無尽 企画書",
  author: "テック無尽実行委員会",
  language: "ja",
  size: "A4",
  entry: [
    { path: "docs/00-cover.md", title: "表紙" },
    { rel: "contents" },
    { path: "docs/01-background.md", title: "1. はじめに（背景・問題意識）" },
    { path: "docs/02-purpose.md", title: "2. イベントの目的" },
    { path: "docs/03-concept.md", title: "3. コンセプト / 思想" },
    { path: "docs/04-overview.md", title: "4. イベント概要" },
    { path: "docs/05-persona.md", title: "5. ターゲット・ペルソナ" },
    { path: "docs/06-program.md", title: "6. コンテンツ構成" },
    { path: "docs/07-timetable.md", title: "7. タイムテーブル（ラフ）" },
    { path: "docs/08-venue-design.md", title: "8. 会場設計（レイアウト・導線）" },
    { path: "docs/09-value.md", title: "9. このイベントが生む価値" },
    { path: "docs/10-participation.md", title: "10. 関わり方（参加・協力メニュー）" },
    { path: "docs/11-sponsorship.md", title: "11. 協賛について" },
    { path: "docs/12-marketing.md", title: "12. 広報・集客計画" },
    { path: "docs/13-organization.md", title: "13. 運営体制" },
    { path: "docs/14-schedule.md", title: "14. スケジュール（準備〜当日）" },
    { path: "docs/15-budget.md", title: "15. 予算計画" },
    { path: "docs/16-risk.md", title: "16. リスクと対策" },
    { path: "docs/17-track-record.md", title: "17. 参考事例" },
    { path: "docs/18-future.md", title: "18. 今後の展望" },
    { path: "docs/19-contact.md", title: "19. お問い合わせ・参加方法" },
    { path: "docs/20-appendix.md", title: "20. 付録" },
  ],
  output: process.env.PDF_OUTPUT_FILE || "techmujin_planning.pdf",
  theme: process.env.VIVLIOSTYLE_THEME || "themes/custom.css",
  toc: {
    title: "目次",
  },
};
